@WebAPI_HostAddress = http://localhost:5265

POST {{WebAPI_HostAddress}}/api/album/
Content-Type: application/json

{
  "title": "title",
  "description": "The album description",
  "accessibility": 2,
  "categoryId": 1
}

###
GET {{WebAPI_HostAddress}}/api/album/1276461256283164672
###
GET {{WebAPI_HostAddress}}/api/albums/0
